from exception import main_exception as exc
from UI import UI_launch

try:
    UI_launch()
except Exception:
    print("dgf")
# exc(UI_launch)
