from exception import main_exception
from UI import UI_launch

operation_dikt = {1: ' + ', 2: ' - ', 3: ' * ', 4: ' / ', 5: ' ^ ', 6: ' // ', 7: ' % '}
main_exception(UI_launch())
